# FTSE 100 Stock Tracker — Ranking Model

## Objective

This notebook ranks FTSE 100 stocks based on return and risk metrics.

The goal is to identify stocks that offer the best risk-adjusted performance.

## Method

Stocks are ranked using:

- Total Return (higher is better)
- Volatility (lower is better)

We combine these into a simple ranking score.

In [1]:
import pandas as pd

df = pd.read_csv("../data/processed/ftse100_metrics.csv")
df.head()

  Unnamed: 0  total_return  volatility
0      AAF.L      2.142623    0.305986
1      AAL.L      0.128531    0.382844
2      ABF.L      0.214130    0.242338
3      ADM.L      0.329857    0.226855
4      AHT.L      0.058456    0.305508

## Ranking logic

We rank stocks based on:

- High return = good
- Low volatility = good

We combine both into a single ranking score.

In [2]:
df["return_rank"] = df["total_return"].rank(ascending=False)

In [3]:
df["risk_rank"] = df["volatility"].rank(ascending=True)

In [4]:
df["score"] = df["return_rank"] + df["risk_rank"]

In [5]:
ranking = df.sort_values("score")
ranking.head(20)

   Unnamed: 0  total_return  volatility  return_rank  risk_rank  score
21      CCH.L      1.459817    0.201192         12.0       12.0   24.0
91     TSCO.L      1.164031    0.194448         23.0        7.0   30.0
46      IHG.L      1.313786    0.213535         18.0       18.0   36.0
41     HSBA.L      1.450690    0.222097         13.0       26.0   39.0
83     SMIN.L      0.650254    0.195061         32.0        8.0   40.0
48      IMB.L      0.554850    0.183577         36.0        5.0   41.0
33     FCIT.L      0.399205    0.140891         44.0        2.0   46.0
49      IMI.L      1.194347    0.222438         20.0       28.0   48.0
66      PCT.L      1.863601    0.234851          8.0       42.0   50.0
5       ALW.L      0.332341    0.138329         49.0        1.0   50.0
61      MNG.L      0.698522    0.217171         31.0       22.0   53.0
8        AV.L      0.435836    0.199626         43.0       10.0   53.0
63       NG.L      0.369935    0.197084         46.0        9.0   55.0
87      SSE.L      0.584903    0.222085         33.0       25.0   58.0
97     WEIR.L      1.090369    0.227736         24.0       34.0   58.0
78     SBRY.L      0.576802    0.221661         34.0       24.0   58.0
69      PSH.L      0.544539    0.221345         37.0       23.0   60.0
40      HLN.L      0.275861    0.191495         55.0        6.0   61.0
65      NXT.L      1.176368    0.231728         21.0       40.0   61.0
37      GSK.L      0.573223    0.222315         35.0       27.0   62.0

In [6]:
ranking.to_csv("../data/processed/ftse100_ranking.csv", index=False)

## Ranking complete

Stocks have been ranked based on total return and volatility.
A lower score indicates better risk-adjusted performance.

The findings from our list show a strong presence of banks and financial companies. Firms such as HSBC and M&G have benefited from higher interest rates and improved margins, which translates to stable and predictable cash flow. Our model rewards companies for delivering solid returns without excessive volatility.

Consumer staple brands are also predominatley seen in the top performers. Companies like Coca Cola and Tesco show good risk adjusted rankings. Their pricing power, stable earnings, and consistent demand allow them to rank highly.  

Overall, these rankings highlight a bigger picture, high growth sectors such as Tech and Oil are missing from our list. Our model appears to be favouring stable cash-flow businesses, ather than high variance sectors.